#!/bin/bash

# Define the names of the containers
FRONTEND_CONTAINER="frontend-container"
BACKEND_CONTAINER="backend-container"
DB_CONTAINER="mysql-container"

# Remove any existing containers
docker stop $FRONTEND_CONTAINER $BACKEND_CONTAINER $DB_CONTAINER 2>/dev/null
docker rm $FRONTEND_CONTAINER $BACKEND_CONTAINER $DB_CONTAINER 2>/dev/null

# Creating a new custom network
docker network create employee-management-network

# Build and run the database container
echo "Building and starting MySQL database container..."
docker build -t database ./database
docker run -d --name $DB_CONTAINER --network employee-management-network -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=employees database

# Build and run the backend container
echo "Building and starting backend container..."
docker build -t backend ./backend
docker run -d --name $BACKEND_CONTAINER --network employee-management-network -p 5000:5000 backend

# Build and run the frontend container
echo "Building and starting frontend container..."
docker build -t frontend ./frontend
docker run -d -p 3000:80 --name $FRONTEND_CONTAINER --network employee-management-network frontend

# Display status of all running containers
echo "All containers are up and running:"
docker ps
